### ISSUE TITLE
Favorite button on classification screen not saving to Favorites

### ISSUE THREAD

**Issue by ksigler** [zooniverse/chimpandsee#106] opened 2016-03-02 00:03 UTC
We've had this issue before, I believe.  When you click the "heart" button to favorite a video during classification, it changes color, but the video isn't saved to Favorites.  Using the Talk function to save a clip to the Favorites collection works as it's supposed to.  [Discussion thread with more detail is here](http://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP00000fb), with the previous problem at the beginning and this most recent occurrence at the end.  Thanks!

**Comment by srallen** [comment] 2016-03-07 21:17
Looks like something is broken. I'm able to replicate, but it isn't obvious what the issue is since there aren't errors in the browser console. I'll have to do some digging to figure it out.

**Comment by AnLand** [comment] 2017-03-10 06:32
Hi! This problem surfaced again (see [discussion](https://talk.chimpandsee.org/#/boards/BCP000000e/discussions/DCP00010fz)) and I can confirm that a friend of mine has the same problem. The favorites button is for him not only working sketchy, but not at all. This is especially a problem for volunteers coming not regularly to Talk. Could you look into that again? Thanks!

**Comment by srallen** [comment] 2017-03-20 14:27
Just wanted to let you know that this is on my radar, but I can't guarantee when I'll get to it. We have a hard deadline for couple of projects launching in the next couple of weeks. I hope to make some time for it this week. Thanks for your understanding.

**Comment by srallen** [comment] 2017-03-20 19:14
@AnLand I'm taking a look at this and it'll take me a moment to remember what might have been going on. I am able to replicate the issue. If you click the button and complete the classification, the newly favorited subject is not showing up in the favorites collection on the profile page. Since there is no error, something is silently failing. I'm investigating the data that is being sent and received from the server to see if something is going wrong there.

**Comment by srallen** [comment] 2017-03-21 19:15
@AnLand There was a bug with the correct workflow id being written into the classification. This wasn't affecting the classification being sent and there is only one workflow for this project, so this bug isn't a big issue for the project. This is now corrected. I checked the site and now I'm seeing subjects show up into my favorites collection correctly when favorited in the classification interface. I'm not totally sure if these were related, but could you check to see if it fixes the issue for you?

**Comment by AnLand** [comment] 2017-03-25 08:27
Thanks @srallen! I tested with three different accounts (from friends) and now it works without any problems. The problem that videos marked as favorites during classification (with the "heart button") has always been included twice in a collection seems to be gone, too. Thanks a lot!

**Comment by srallen** [comment] 2017-03-27 13:55
Ok great! It sounds like this is fixed now, so I'll close the issue.

**Closed by srallen** 2017-03-27 13:55 UTC
